spring.application.name=aut-svc
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=system
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

jwt.secret=5f2c8b9e1a4d6f70c3b8e2a9d4f1c6b7e0a3d5f8c2b9e4a7d0f3c6b1e8a5d2f9
jwt.expiration=86400000

# https://myaccount.google.com/apppasswords
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kushanherath59@gmail.com
spring.mail.password=cuwa flrd wgaq quwg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

otp.expiry-ms=300000